config/routes.rb
Merchdash::Application.routes.draw do
  get "pages/home"
  get "pages/contact"
  

  
  

  devise_for :users
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get "/register" => "devise/registrations#new"
  end

  authenticated :user do
    root to: "bands#index", as: :authenticated_root
  end

  unauthenticated do
    root to: "pages#home"
  end
 

  resources :bands do
    resources :events
  end

      

end

app/models/band.rb
class Band < ActiveRecord::Base

	#attr_accessible :name, :user_id, :events_attributes

	belongs_to :user

	has_many :events, :dependent => :destroy
  accepts_nested_attributes_for :events, :reject_if => proc { |a| a[:place].blank? }, :allow_destroy => true

end

app/models/event.rb
class Event < ActiveRecord::Base
	#attr_accessible :date, :place, :band_id
	belongs_to :band
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bands, :dependent => :destroy
  accepts_nested_attributes_for :bands, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bands_controller.rb
class BandsController < InheritedResources::Base
	before_filter :authenticate_user!

	def new
		@user = current_user
		@band = Band.new
		event = @band.events.build
	end

	def create
		# @band = current_user.bands.create(params[:band])
		@band = current_user.bands.create(permitted_params)
		if @band.save
			redirect_to [@band]
		else
			render :edit
		end
	end
  
  def update
    @band = current_user.bands.find(params[:id])
    if(@band.update_attributes(permitted_params))
      redirect_to @band
    else
      render :edit
    end
  end
  
	def show
		@band = Band.find(params[:id])
		event = @band.events.build
	end

	private

	def permitted_params
    params.require(:band).permit(:name, :user_id, events_attributes: [:id, :date, :place, :band_id])
	end
end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base

	def permitted_params
		params.require(:event).permit(:date, :place, :band_id)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bands/_event_fields.html.erb
<p>
	<%= f.label :place, "City" %><br/>
	<%= f.text_field :place %> <br/>
	<%= f.label :date, "Date" %><br/>
	<%= f.date_select :date %></p>
</p>

app/views/bands/index.html.erb
<h1>Your bands</h1>

<p><%= link_to " Log out", logout_path %></p>
<p><%= link_to "New band", new_band_path %></p>
<p>
	<ul>
		<% @bands.each do |band| %>
			<li><%= link_to band.name, band %></li>
		<% end %>
	</ul>
</p>

app/views/bands/new.html.erb
<h1>Create new band</h1>


<%= form_for @band do |f| %>


	<%=f.label :name %>
	<%=f.text_field :name %>
	<h1>Create your first selling event</h1>
	<% @band.events.each do |event| %>
    <%=f.fields_for :events, event do |builder| %>
      <%= render 'event_fields', :f => builder %> 
    <% end %>
  <%end%>
	<%= f.submit "Submit" %>

<% end %>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<p><%= link_to "Band Overview", bands_path %></p>

<%= form_for @band do |f| %>

	<h1>Create a new selling event</h1>  

  <% @band.events.each do |event| %>
    <%=f.fields_for :events, event do |builder| %>
      <%= render 'event_fields', :f => builder %> 
    <% end %>
  <%end%>

	<%= f.submit "Submit" %>

<% end %>

<p>
	<ul>
		<% @band.events.each do |event| %>
			<li><%= event.place %></li>
		<% end %>
	</ul>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Merchdash</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p><%= link_to "Log in", login_path  %></p>
<p><%= link_to "Register", register_path  %></p>